### ISSUE TITLE
Setup an apt repository

### ISSUE THREAD

**Issue by fornwall** [termux/termux-root-packages#1]
Anyone interested in maintaining a root-only repo?

**Comment by Auxilus** [comment]
I am!

**Comment by Auxilus** [comment]
do I have to build debs for all arches manually or do I get em from travis artifacts?

**Comment by Grimler91** [comment]
@Auxilus I believe we want to cross compile the packages in the docker image and get the the debs from there. You then need docker. 

@fornwall I could setup and maintain the repo as well, preferably at grimler.se as github.io's caching makes it none-ideal for package hosting.
Would this be an acceptable setup?

**Comment by Auxilus** [comment]
@Grimler91 Nice Work, thanks for hosting the repo

**Comment by Auxilus** [comment]
@Grimler91  I've updated the wiki, plz check if it's correct
https://wiki.termux.com/wiki/Package_Management#Installing_root_packages

Thanks

**Comment by Grimler91** [comment]
@Auxilus looks good, thanks

**Comment by fornwall** [comment]
@Grimler91 Nice work, I made an invitation for you to be admin of this repo!

**Comment by isrgish** [comment]
Is this repo still working? When I tried to download the key I got an error that there is no keyserver available. If I try to upgrade I get the following

[u0_a100 …/~]$ pkg upgrade                                                          Hit:1 https://termux.net stable InRelease
Get:2 https://grimler.se root InRelease [4043 B]
Get:3 https://grimler.se root/stable aarch64 Packages [6416 B]
Err:3 https://grimler.se root/stable aarch64 Packages
  Writing more data than expected (6600 > 6416)
  Hashes of expected file:
   - Filesize:6416 [weak]
   - SHA512:773b4eb3a76affb54fb4bd994816ee865b5e757cd0315905b81717f719f248a30aee3a9571e7a1de28499ebccfb3db44173e3621a56a277dc63d775aae3098b9
   - SHA256:47fa85195f0844a7905409a6d721c5210b2a01350f2821fdcc2e52b305f68689
   - SHA1:644854a78f7680c7429425879d90535a27350e55 [weak]
   - MD5Sum:ea52bbda7d93cd7af21136546dd405c7 [weak]
  Release file created at: Mon, 17 Dec 2018 06:16:54 +0000
Fetched 4043 B in 1s (2571 B/s)
Reading package lists... Done
E: Failed to fetch https://grimler.se/dists/root/stable/binary-aarch64/Packages.xz  Writing more data than expected (6600 > 6416)
   Hashes of expected file:
    - Filesize:6416 [weak]
    - SHA512:773b4eb3a76affb54fb4bd994816ee865b5e757cd0315905b81717f719f248a30aee3a9571e7a1de28499ebccfb3db44173e3621a56a277dc63d775aae3098b9
    - SHA256:47fa85195f0844a7905409a6d721c5210b2a01350f2821fdcc2e52b305f68689
    - SHA1:644854a78f7680c7429425879d90535a27350e55 [weak]
    - MD5Sum:ea52bbda7d93cd7af21136546dd405c7 [weak]
   Release file created at: Mon, 17 Dec 2018 06:16:54 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by vmari** [comment]
> Is this repo still working? When I tried to download the key I got an error that there is no keyserver available. If I try to upgrade I get the following
> 
> [u0_a100 …/~]$ pkg upgrade Hit:1 https://termux.net stable InRelease
> Get:2 https://grimler.se root InRelease [4043 B]
> Get:3 https://grimler.se root/stable aarch64 Packages [6416 B]
> Err:3 https://grimler.se root/stable aarch64 Packages
> Writing more data than expected (6600 > 6416)
> Hashes of expected file:
> 
> * Filesize:6416 [weak]
> * SHA512:773b4eb3a76affb54fb4bd994816ee865b5e757cd0315905b81717f719f248a30aee3a9571e7a1de28499ebccfb3db44173e3621a56a277dc63d775aae3098b9
> * SHA256:47fa85195f0844a7905409a6d721c5210b2a01350f2821fdcc2e52b305f68689
> * SHA1:644854a78f7680c7429425879d90535a27350e55 [weak]
> * MD5Sum:ea52bbda7d93cd7af21136546dd405c7 [weak]
>   Release file created at: Mon, 17 Dec 2018 06:16:54 +0000
>   Fetched 4043 B in 1s (2571 B/s)
>   Reading package lists... Done
>   E: Failed to fetch https://grimler.se/dists/root/stable/binary-aarch64/Packages.xz  Writing more data than expected (6600 > 6416)
>   Hashes of expected file:
>   - Filesize:6416 [weak]
>   - SHA512:773b4eb3a76affb54fb4bd994816ee865b5e757cd0315905b81717f719f248a30aee3a9571e7a1de28499ebccfb3db44173e3621a56a277dc63d775aae3098b9
>   - SHA256:47fa85195f0844a7905409a6d721c5210b2a01350f2821fdcc2e52b305f68689
>   - SHA1:644854a78f7680c7429425879d90535a27350e55 [weak]
>   - MD5Sum:ea52bbda7d93cd7af21136546dd405c7 [weak]
>   Release file created at: Mon, 17 Dec 2018 06:16:54 +0000
>   E: Some index files failed to download. They have been ignored, or old ones used instead.

I have the same problem here

**Comment by Grimler91** [comment]
@isrgish @vmari Should be fixed now, thanks for reporting!
I didn't regenerate the InRelease file, only the Release file (by mistake), which meant that an outdated InRelease file was sitting in the repo causing problems
