### ISSUE TITLE
HW-Probe

### ISSUE THREAD

**Issue by Mannshoch** [termux/termux-root-packages#101]
Please add HW-Probe to be able to check easy which hardware is currently supported by linux.

**Package description**
> This is a project to collect hardware details of Linux-powered computers over the world and help Linux users and developers to collaboratively debug hardware related issues. 

> Hardware Probe Tool (HW Probe) — a tool to probe for hardware, check its operability and upload result to the Linux hardware database

**Link to home page and sources**
1. Home page: https://linux-hardware.org
2. Source code: https://github.com/linuxhw/hw-probe
3. Examples: https://linux-hardware.org/index.php?view=timeline

**Additional information**
I simply tried to run hw-probe.pl but it says "hwinfo" is missing.

**Comment by xeffyr** [comment]
Package is available via:
```
pkg install root-repo
pkg install hw-probe
```

**Comment by linuxhw** [comment]
Hi,
@Mannshoch 

Could you please help me to identify hardware model and Android version of probed smartphones? Which files should be collected by hw-probe to identify the smartphone?

Thanks.

**Comment by Mannshoch** [comment]
Hi @linuxhw  
I'm not the right person for this question. I'm only an interested User and do not have deeper knowledge.
