### ISSUE TITLE
Tshark doesn't detect any packets

### ISSUE THREAD

**Issue by HoangPhantom** [termux/termux-root-packages#111]
After upgrading tshark to version 3.0.2, I cannot scan my network to do pentesting. After executing the command, it displays:
![20190716_115309](https://user-images.githubusercontent.com/46418295/61267057-6f0a0d80-a7c0-11e9-81bd-6649ffc8f05a.png)
The scan command doesn't even detect anything from my wifi. The show all interfaces only display those two. Am I missing something.
My Termux-info:
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-21 unstable/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.72 #1 SMP PREEMPT Tue Feb 16 18:23:49 CST 2016 armv7l Android
Termux-packages arch:
arm
Android version:
5.1
Device manufacturer:
Lenovo
Device model:
Lenovo TB3-710I

I hope you can help and fix this. Thank you very much.

**Comment by HoangPhantom** [comment]
Hello, I would like to know if this bug has been fixed or is in progress. I apologize if I sound impatient.

**Comment by Grimler91** [comment]
Hi, I haven't looked at it.

Do you get the same behavior when running under tsu instead of with tsudo?

I've updated tshark to 3.0.3, check if that makes a difference.

**Comment by HoangPhantom** [comment]
![20190721_160206](https://user-images.githubusercontent.com/46418295/61589218-15934b80-abd1-11e9-956d-e6f6bae9bdb6.png)
My tshark version is still at 3.0.2

**Comment by Grimler91** [comment]
@HoangPhantom Yeah, you need to run `apt update && apt upgrade` to get the latest version

**Comment by HoangPhantom** [comment]
It succeeded, thank you very much for the quick response.
