### ISSUE TITLE
Package request: ettercap

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-root-packages#116]
Homepage: https://www.ettercap-project.org/

**Comment by IRISnoir** [comment]
Excuse me, can I know if this package is being worked on? I am very sorry if I sound impatient.

**Comment by Grimler91** [comment]
@IRISnoir Hi, no, I haven't looked at it. Looks pretty straightforward though so can give it a try now.

**Comment by Grimler91** [comment]
Package added in https://github.com/termux/termux-root-packages/pull/122.
