### ISSUE TITLE
Terminal Modprobe Rfkill modül

### ISSUE THREAD

**Issue by Klavyeli** [termux/termux-root-packages#124]
After updating the terminal, such a set of errors, how can I get the necessary modules "modprobe" "rfkill" termux
![Screenshot_20190828-185826](https://user-images.githubusercontent.com/38491552/63872656-c0fca080-c9c6-11e9-9375-4af81b5e0e90.jpg)

**Comment by Klavyeli** [comment]
The device is already rooted

**Comment by Klavyeli** [comment]
What is the installation command of the module changed commands

**Comment by Grimler91** [comment]
If you are rooted then you might have modprobe and/or rfkill in /system/bin, or as part of a system installed busybox, so you could setup a symlink for it. 
Rfkill and modprobe shouldn't be necessary for running aircrack though.

Your screenshot shows that you have bcm43455. Monitor mode seems to be possible on this chip if you install a custom driver (but doing so is out of scope here).

**Comment by xeffyr** [comment]
rfkill in most cases is compiled-in and is not available as `*.ko` file. Modprobe is useless in this case.

Also, monitor mode can be enabled with `iwconfig` from wireless-tools package (tested with [my](https://github.com/xeffyr/android_kernel_samsung_herolte) kernel):
```
iwconfig wlan1 mode monitor
```
**Monitor mode works only if wi-fi firmware blobs allow that.**

**Comment by Klavyeli** [comment]
Problem solved when I scanned module codes in / system / bin

**Comment by tailorsmit** [comment]
> Problem solved when I scanned module codes in / system / bin

How to scan module in /system/bin?? (Better with screen shot ) thanks
