### ISSUE TITLE
feature request : Termux in Docker

### ISSUE THREAD

**Issue by zaoqi** [termux/termux-root-packages#125]
I want to run [Docker image running Termux](https://github.com/Rudloff/termux-docker-image) in CI

**Comment by RossComputerGuy** [comment]
Thats impossible on a non rooted device

**Comment by zaoqi** [comment]
@RossComputerGuy This isn't `docker on android`

**Comment by xeffyr** [comment]
What you are looking for is https://github.com/Rudloff/termux-docker-image.
