### ISSUE TITLE
termshark no longer runs on Android Q

### ISSUE THREAD

**Issue by gcla** [termux/termux-root-packages#132]
**Problem description**

Termshark is a TUI interface for tshark, written in Go/golang. The binary no longer runs. I receive the following error:

`error: "termshark": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic`

**Steps to reproduce**

```bash
pkg install termshark
termshark -h
```

**Expected behavior**

Termshark should display its help page.

**Additional information**

```
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 4.9.165-gfff483291c07-ab5725533 #0 SMP PREEMPT Fri Jul 12 22:55:38 UTC 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
10
Device manufacturer:
Google
Device model:
Pixel 3
```

I am sure this problem is linked to this issue: https://github.com/termux/termux-packages/issues/3619

Termshark is written using Go/golang. A couple of weeks back, I upgraded my phone to the latest android release, Android Q. The suggestion in the linked issue was that the problem may be resolved by having termux packages recompiled with Go 1.13. It looks to me as though `termux_setup_golang` is now using Go 1.13. Perhaps the regular termux Go packages were recompiled, but not the termux root packages? (Just guessing)

I'm more than happy to fix this with a prod in the right direction, and don't want to burden anyone since this is my own package.

**Comment by xeffyr** [comment]
Rebuilt packages should be available shortly.

**Comment by gcla** [comment]
It works again, thank you!
