### ISSUE TITLE
Reading package lists... Done E: The repository 'https://termux-x11.ml x11 Release' does not have a Release file. N: Updating from such a repository can't be done securely, and is therefore disabled by default. N: See apt-secure(8) manpage for repository creation and user configuration details. W: GPG error: https://hax4us.github.io/termux-tools extras InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A13A121F25D06F7 $

### ISSUE THREAD

**Issue by aimen2010** [termux/termux-root-packages#133]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by RossComputerPerson** [comment]
Run `gpg --recv-keys 5A13A121F25D06F7`

**Comment by aimen2010** [comment]
tanks،But the same problem has been broadcast, see

gpg --recv-keys 5A13A121F25D06F7
The program 'gpg' is not installed. Install it by executing:
 pkg install gnupg
$ pkg install gnupg
Hit:1 https://termux.net stable InRelease
Ign:2 https://termux-x11.ml x11 InRelease
Err:3 https://termux-x11.ml x11 Release
  404
Ign:4 https://dl.bintray.com/grimler/game-packages-21 games InRelease
Get:5 https://hax4us.github.io/termux-tools extras InRelease [5670 B]
Ign:6 https://dl.bintray.com/grimler/termux-root-packages-21 root InRelease
Ign:7 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Ign:8 https://dl.bintray.com/xeffyr/unstable-packages-21 unstable InRelease
Get:9 https://dl.bintray.com/grimler/game-packages-21 games Release [5344 B]
Hit:9 https://dl.bintray.com/grimler/game-packages-21 games Release
Ign:5 https://hax4us.github.io/termux-tools extras InRelease
Get:10 https://dl.bintray.com/grimler/termux-root-packages-21 root Release
[6185 B]
Hit:10 https://dl.bintray.com/grimler/termux-root-packages-21 root Release
Get:13 https://dl.bintray.com/grimler/science-packages-21 science Release
[5348 B]
Hit:13 https://dl.bintray.com/grimler/science-packages-21 science Release
Get:15 https://dl.bintray.com/xeffyr/unstable-packages-21 unstable Release
[6065 B]
Hit:15 https://dl.bintray.com/xeffyr/unstable-packages-21 unstable Release
Reading package lists... Done
E: The repository 'https://termux-x11.ml x11 Release' does not have a
Release file.
N: Updating from such a repository can't be done securely, and is therefore
disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration
details.
W: GPG error: https://hax4us.github.io/termux-tools extras InRelease: The
following signatures couldn't be verified because the public key is not
available: NO_PUBKEY 5A13A121F25D06F7
$ gpg --recv-keys 5A13A121F25D06F7
The program 'gpg' is not installed. Install it by executing:
 pkg install gnupg
$

في الجمعة، 27 سبتمبر، 2019 14:57 Tristan Ross <notifications@github.com>
كتب:

**Comment by RossComputerPerson** [comment]
Maybe reinstalling termux or running `pkg update` will fix the issue.

**Comment by aimen2010** [comment]
This proved and other writings I did not understand 
mkdir -p $PREFIX/etc/apt/sources.list.d && printf "deb [trusted=yes] https://hax4us.github.io/termux-tools/ extras main" > $PREFIX/etc/apt/sources.list.d/hax4us.list

**Comment by aimen2010** [comment]
My friend, if you have an Instagram or Telegram account come give you pictures of my problem,

**Comment by xeffyr** [comment]
Closing since third-party repositories are **off-topic** here.

You should remove `https://termux-x11.ml` from your sources.list. Btw, why not to view page https://termux-x11.ml/ in browser... there's all needed information.

Regarding `W: GPG error: https://hax4us.github.io/termux-tools extras` - just ignore it, that's warning only.
