### ISSUE TITLE
Bettercap ip error

### ISSUE THREAD

**Issue by H4ck3r404** [termux/termux-root-packages#143]
I'm having this error:
_          _   _
| |__   ___| |_| |_ ___ _ __ ___ __ _ _ __
| '_ \ / _ \ __| __/ _ \ '__/ __/ _` | '_ \
| |_) |  __/ |_| ||  __/ | | (_| (_| | |_) |
|_.__/ \___|\__|\__\___|_|  \___\__,_| .__/
                                     |_| v1.6.2
http://bettercap.org/

[I] Starting [ spoofing:✔ discovery:✔ sniffer:✘ tcp-proxy:✘ udp-proxy:✘ http-proxy:✘ https-proxy:✘ sslstrip:✘ http-server:✘ dns-server:✘ ] ...

[E] '' is not a valid IP or MAC address.
How should I fix it?

**Comment by Grimler91** [comment]
What did you run to get this error?

**Comment by H4ck3r404** [comment]
sudo bettercap
(Sudo from https://gitlab.com/st42/termux-sudo)

**Comment by H4ck3r404** [comment]
For instalation:
gem install bettercap

**Comment by H4ck3r404** [comment]
update
I've tried this script from bettercap website before installing from gem:

sudo su
mount -o rw,remount /
mkdir -p /home/builder/.termux-build/_cache/18-arm-21-v2/bin/
ln -s `which pkg-config` /home/builder/.termux-build/_cache/18-arm-21-v2/bin/arm-linux-androideabi-pkg-config

**Comment by Grimler91** [comment]
> For instalation:
> gem install bettercap

Uninstall bettercap through gem and install it from the root repo instead with 
```
gem uninstall bettercap
pkg install root-repo
apt install bettercap
```

And then try again. The bettercap from gem isn't patched to work in termux

**Comment by H4ck3r404** [comment]
Thanks.
