### ISSUE TITLE
Monitor mode not changing

### ISSUE THREAD

**Issue by Z3wn** [termux/termux-root-packages#153]
![Screenshot_2020-01-06-00-17-09-262_com termux](https://user-images.githubusercontent.com/59116834/71783789-1f432b00-301a-11ea-8512-db47e9e39d62.jpg)

**Comment by Grimler91** [comment]
Yes.. You need to tell it which interface to use. Read the man page: https://linux.die.net/man/1/airmon-ng

**Comment by Z3wn** [comment]
![Screenshot_2020-01-06-10-19-04-050_com termux](https://user-images.githubusercontent.com/59116834/71794049-18de9e80-306e-11ea-9572-e50242a04ce5.jpg)
Still got error. There is no interface.
