### ISSUE TITLE
Sudo

### ISSUE THREAD

**Issue by Z3wn** [termux/termux-root-packages#154]
https://www.sudo.ws/

Sudo for termux.

**Comment by Grimler91** [comment]
Termux is a single-user system, so what exactly do you want [sudo](https://www.sudo.ws/) to do for you?

**Comment by xeffyr** [comment]
Sudo from https://www.sudo.ws/ is PAM-based but Termux does not use PAM for reason mentioned above.

Use `tsudo` from package `tsu`.
