### ISSUE TITLE
Package request: pixiewps

### ISSUE THREAD

**Issue by drygdryg** [termux/termux-root-packages#156]
**Package description**
An offline Wi-Fi Protected Setup brute-force utility.

**Link to home page and sources**
Home page and source code: https://github.com/wiire-a/pixiewps

**Additional information**
I have successfully built pixiewps on my device.
Build requirements: build-essential, pkg-config
Build guide:
```
pkg install git build-essential pkg-config
git clone https://github.com/wiire-a/pixiewps.git
cd pixiewps/
make
make install
```

**Comment by drygdryg** [comment]
Built it on my device, but statically linked binaries cause a segmentation fault on some devices.
Binaries is here: https://github.com/drygdryg/OneShot_Termux_installer/tree/master/binaries

**Comment by FreddieOliveira** [comment]
Added in https://github.com/termux/termux-root-packages/commit/ef5c3d7d247086c16ebe13b3461114dc3ee979b3.

@Grimler91 I believe this can be closed now
