### ISSUE TITLE
where is build-root-package.sh

### ISSUE THREAD

**Issue by diehard88** [termux/termux-root-packages#167]
couldn't find it.

**Comment by Grimler91** [comment]
Thanks! I forgot to edit the README before. 

You can use the ./build-package.sh script in the termux-root-packages folder for building a root package

**Comment by radinmoradi** [comment]
در تاریخ یکشنبه ۲۳ فوریهٔ ۲۰۲۰،‏ ۱۴:۵۸ Henrik Grimler <
notifications@github.com> نوشت:

**Comment by radinmoradi** [comment]
در تاریخ یکشنبه ۲۳ فوریهٔ ۲۰۲۰،‏ ۱۴:۵۸ Henrik Grimler <
notifications@github.com> نوشت:

**Comment by RossComputerGuy** [comment]
What?
