### ISSUE TITLE
Package frida

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-root-packages#17]
_From @radare on November 10, 2016 13:59_

http://frida.re

_Copied from original issue: termux/termux-packages#551_

**Comment by Grimler91** [comment]
_From @radare on November 10, 2016 14:0_

cc @oleavr

**Comment by Grimler91** [comment]
I guess you're mostly interested in frida-server, which requires root. 

Please open an issue at https://github.com/termux/termux-root-packages instead, I'll look into compiling it in the near future.

**Comment by Grimler91** [comment]
Building static binaries of frida-server is pretty straightforward, but it would be nicer to link it dynamically, which would rather large patching of the Makefiles. 
Frida use libdwarf (rather than libdw) so we might need to add that package as well (I've ported it [here](https://github.com/Grimler91/termux-packages/tree/libdwarf)).

I'm using this repo as a playground for frida: https://github.com/Grimler91/termux-root-packages/tree/frida.

**Comment by oleavr** [comment]
Cool! The reason Frida's build system is statically linking all of its dependencies is because otherwise there'll be situations where it's unsafe to use Frida to dynamically instrument those same libraries as used by other processes. Another challenge is that we have our own forks of some of the dependencies, so if those are installed they would also have to be renamed to avoid compatibility issues. (E.g. we heavily patch GLib so it is able to clean up statically allocated resources, and some other things that are required for Frida's use-cases.)

**Comment by oleavr** [comment]
> So glib is built from https://github.com/frida/glib then I presume?

Correct! We also depend on our forks of the other dependencies – see `Makefile.sdk.mk`. It's also important to use our fork of the Vala compiler. (All of these changes is why we prebuild the dependencies and toolchain things, as it's just too much to ask every user to build them all correctly.)

**Comment by Grimler91** [comment]
frida-server and frida-inject are now added to this repo (under the name package name frida-server). 

I used r17 NDK but left pretty much everything else as is.
I didn't rebuild the sdk, but some simple tests seem to work, I'll leave that for future work if anyone encounters problems.

**Comment by ftopan80** [comment]
My kind sir, please also build frida-tools, frida-python and frida-node, if possible.

**Comment by Grimler91** [comment]
@ftopan80 sorry, forgot to answer here. Frida-python and frida-node would be really cool. Building them for arm and aarch64 isn't supported by the frida build system right now though and I am not sure how much work it would mean to implement it, @oleavr probably has more information.

**Comment by oleavr** [comment]
@Grimler91 Awesome! Shouldn't be too bad given we already cross-compile everything else for Android. Definitely happy to assist if anybody's interested in taking a stab at it.

**Comment by Grimler91** [comment]
@oleavr Cool, I'll give it another try then!

**Comment by AarifZ** [comment]
Is there a way I can run frida without pc using termux? 
I'm getting libresolv.so.2 not found error if I'm trying to run anything

**Comment by Grimler91** [comment]
@AarifZ Could you give me steps to reproduce that issue?

**Comment by AarifZ** [comment]
@Grimler91 the error I'm facing is 

```***
Failed to load the Frida native extension: dlopen failed: library "libresolv.so.2" not found
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "android-hook.py", line 1, in <module>
    import frida
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/frida/__init__.py", line 24, in <module>
    raise ex
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/frida/__init__.py", line 7, in <module>
    import _frida
ImportError: dlopen failed: library "libresolv.so.2" not found````

I just did pip install frida and pip install frida-tools
$cd my_repo 

$python android-hook.py get_poke_stats.js com.nianticlabs.pokemongo 

And I got the error

**Comment by Grimler91** [comment]
Yeah, so, as discussed above: the python bindings haven't been compiled for termux so they won't work in termux for now.

**Comment by AarifZ** [comment]
Any alternate method to make it work?

**Comment by radare** [comment]
r2pm -i r2frida

r2frida is easier to build and it works from termux

will be good to package it in termux too

**Comment by gMan1990** [comment]
> Yeah, so, as discussed above: the python bindings haven't been compiled for termux so they won't work in termux for now.

https://pypi.org/project/frida/12.6.12/#files frida-12.6.12-py3.5-linux-aarch64.egg
It can works?
