### ISSUE TITLE
some question about frida-python

### ISSUE THREAD

**Issue by stuven1989** [termux/termux-root-packages#179]
hi,  I know you cross compile frida sucessfully.  I try to cross compile frida-python for android-arm64, but the result is to reboot device. do you know this reason, If it's convenient for you, can you give me a compiled package, thank you!

**Comment by Grimler91** [comment]
Hi, so it reboots when you have built it yourself? Or does it reboot during the compilation?

Have you tried the version I have packaged (which you can install with `apt update && apt install root-repo && apt install frida-python`)?

I was experiencing reboots at first but they disappeared for some reason: https://github.com/termux/termux-root-packages/issues/169

**Comment by stuven1989** [comment]
@Grimler91 hi, I use frida-python that is build in x86_64, When I call 'spawn' function, it lead to reboot the device. I only need python interpreter which has frida-python without frida-server etc, the frida-python has '_frida.so' file. The restart problem has been bothering me for weeks, I have no idea, do you have '_frida.so' file for android-arm64? if you hava, please send to me , thank you!!

**Comment by Grimler91** [comment]
You can install frida-python, which includes _frida.so,  with the instructions I wrote.. Download the deb and extract it with `ar x` + `tar xf` if you do not want to install frida-server as well.

**Comment by stuven1989** [comment]
hi , where to download?

**Comment by Grimler91** [comment]
I do not understand what you mean. 

Are you using termux? Then run `apt update && apt install root-repo && apt install frida-python` or `apt download frida-python`, or find the deb in https://dl.bintray.com/grimler/termux-root-packages-24/.

If you are not using termux then this library will obviously not work for you, it is compiled against the python that termux uses.
