### ISSUE TITLE
Package Request: MDK4

### ISSUE THREAD

**Issue by glblduh** [termux/termux-root-packages#180]
This package would add more wifi penetration testing tools to Termux

**Package description**
MDK4 is a Wi-Fi testing tool from E7mer of 360, ASPj of k2wrlz, it uses the osdep library from the aircrack-ng project to inject frames on several operating systems. 

**Link to home page and sources**
1. Home page:
https://github.com/aircrack-ng/mdk4
2. Source code:
https://github.com/aircrack-ng/mdk4

**Comment by gitdebpro** [comment]
Hi there follow is the build.sh of mdk4 tested on armhf but not on arm64 bit
[mdk4.zip](https://github.com/termux/termux-root-packages/files/6311578/mdk4.zip)

**Comment by gitdebpro** [comment]
> 
> 
> This package would add more wifi penetration testing tools to Termux
> 
> **Package description**
> MDK4 is a Wi-Fi testing tool from E7mer of 360, ASPj of k2wrlz, it uses the osdep library from the aircrack-ng project to inject frames on several operating systems. 
> 
> **Link to home page and sources**
> 1. Home page:
> https://github.com/aircrack-ng/mdk4
> 2. Source code:
> https://github.com/aircrack-ng/mdk4

just type "apt install mdk4" its available now.

Regards.

**Comment by Grimler91** [comment]
Added in https://github.com/termux/termux-root-packages/commit/48be2f13705f616af2e2eab0b8c298ec86ec60e7
