### ISSUE TITLE
sudo can't find superuser binaries

### ISSUE THREAD

**Issue by H4ck3r404** [termux/termux-root-packages#187]
Running anything using sudo shows:

No superuser binary detected.
Are you rooted?

Except su command is working properly.
Phone is rooted using SuperSU, which doesn't show up toast message when using sudo. Before update everything worked properly.

**Comment by Grimler91** [comment]
It's a problem with the [tsu package](https://github.com/cswl/tsu) (seems it only works with magisk for some reason), could you open an issue in that repo?

**Comment by H4ck3r404** [comment]
No problem.

**Comment by profread** [comment]
How did you fix this issue

**Comment by H4ck3r404** [comment]
Just use this:
https://github.com/st42/termux-sudo

**Comment by Alireza1369newi** [comment]
> Running anything using sudo shows:
> 
> No superuser binary detected.
> Are you rooted?
> 
> Except su command is working properly.
> Phone is rooted using SuperSU, which doesn't show up toast message when using - [ ] sudo. Before [](pdate everything worked properly.
