### ISSUE TITLE
Package: Arp-Scan

### ISSUE THREAD

**Issue by DarrenRainey** [termux/termux-root-packages#19]
Just wondering if someone could port arp-scan to termux.

**Comment by Grimler91** [comment]
Please try this deb: https://grimler.se/dists/testing/misc/binary-aarch64/dnsmasq_2.79_aarch64.deb (replace aarch64 with your arch if needed). 

I want to run a test in a i686 emulator to check a configure option but it builds at least.

**Comment by DarrenRainey** [comment]
ok I'll test this later but currrently the arp-scan binary I have I can confirm is working on armhf (ARM-V7)

**Comment by Grimler91** [comment]
Package is now available from repository.

**Comment by Testato** [comment]
I tried to install it in termux but fo not found the package

$ apt install arp-scan
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package arp-scan

**Comment by Grimler91** [comment]
@Testato you need to subscribe to the root repo. See the readme: https://github.com/termux/termux-root-packages/blob/master/README.md#subscribing-to-the-repository
