### ISSUE TITLE
Package request: dnsmasq

### ISSUE THREAD

**Issue by hexvalid** [termux/termux-root-packages#20]
Awesome DNS forwarder and DHCP server.

**Comment by Grimler91** [comment]
Please try this package: https://grimler.se/dists/testing/misc/binary-aarch64/dnsmasq_2.79_aarch64.deb
and confirm that root is required. Replace aarch64 with your arch if you are using another one.

**Comment by Grimler91** [comment]
Package is now available from repository.

**Comment by AhmadNaruto** [comment]
> Package is now available from repository.

i cant find in repo.. 
cant install with pkg install dnsmasq

**Comment by ravener** [comment]
@AhmadNaruto did you first do `pkg install root-repo`? You also need to be rooted

**Comment by conhibit** [comment]
> @AhmadNaruto did you first do `pkg install root-repo`? You also need to be rooted

What if my phone isnt rootable yet???  Termux is supposed to be NONroot compatible!

**Comment by Grimler91** [comment]
> What if my phone isnt rootable yet???

Then you cannot (succesfully) use packages from termux-root-packages

> Termux is supposed to be NONroot compatible!

It is, but not packages in termux-root-packages

**Comment by conhibit** [comment]
> > What if my phone isnt rootable yet???
> 
> Then you cannot (succesfully) use packages from termux-root-packages
> 
> > Termux is supposed to be NONroot compatible!
> 
> It is, but not packages in termux-root-packages

Weak as fuck dawg!

Oh well i just learnt i gotta buy a usb wifi card just to use all wifi tools so I waisted a fuckton of time neways..

I hate my life
