### ISSUE TITLE
Frida connection to server and errors

### ISSUE THREAD

**Issue by blap** [termux/termux-root-packages#204]
Hi,

When I type `frida-ps` I get `Unable to load SElinux policy from kernel: Failed to open file "/sys/fs/selinux/policy": Permission denied`. But it's ok because it runs, but only shows bash, termux and python.

When I type `frida-ls-devices`, the same error and my device `socket`.

So I tried to connect frida to frida-server (in this case: magisk-frida - `frida-ps -D socket` ) it shows all PIDs and Names. But when I put `frida-ps` it only shows again bash, termux and python. In other words, I think the connection was lost.

When I tried to connect frida to frida-server (in this case: frida-server from termux - `frida-ps -D socket`) it only shows bash, termux and python.

How can I get frida to show the list of processes running on the device?

**Comment by Grimler91** [comment]
Hi,

> Unable to load SElinux policy from kernel: Failed to open file "/sys/fs/selinux/policy": Permission denied

> frida-ps -D socket) it only shows bash, termux and python.

Sounds like you are not running frida-{server,ps} as root? Run them in a tsu shell.

**Comment by blap** [comment]
> 
> 
> Hi,
> 
> > Unable to load SElinux policy from kernel: Failed to open file "/sys/fs/selinux/policy": Permission denied
> 
> > frida-ps -D socket) it only shows bash, termux and python.
> 
> Sounds like you are not running frida-{server,ps} as root? Run them in a tsu shell.

But if I put `su` [enter], and then `frida-ps` termux says `frida-ps: not found`.

**Comment by Grimler91** [comment]
> But if I put su [enter], and then frida-ps termux says frida-ps: not found

Try with `tsu`, otherwise the environmental variables (like PATH) are reset to android's standard one.

If frida-server works from a su shell (without specifying /data/data/com.termux/files/usr/bin/frida-server), then it is probably using a frida-server binary from somewhere else on your device.

**Comment by blap** [comment]
> Try with `tsu`, otherwise the environmental variables (like PATH) are reset to android's standard one.
> 
> If frida-server works from a su shell (without specifying /data/data/com.termux/files/usr/bin/frida-server), then it is probably using a frida-server binary from somewhere else on your device.

`tsu` did the magic! Thanks!

But when I try to run a script (xxx.js is in termux home), like `frida --no-pause -l xxx.js -f com.example.app` 
I got 
`CANNOT LINK EXECUTABLE "/data/local/tmp/frida-9439fdd4f5172e868216bbaf1fa13fa5/frida-helper-32": "/data/data/com.termux/files/usr/lib/libtermux-exec.so is 64-bit instead of 32-bit" Failed to spawn: unexpectedly timed out while spawning helper process`

awkward...

**Comment by blap** [comment]
`unset LD_PRELOAD` skip `CANNOT LINK EXECUTABLE "/data/local/tmp/frida-9439fdd4f5172e868216bbaf1fa13fa5/frida-helper-32": "/data/data/com.termux/files/usr/lib/libtermux-exec.so is 64-bit instead of 32-bit"`  and only give `Failed to spawn: unexpectedly timed out while spawning helper process` ...

**Comment by Grimler91** [comment]
> `unset LD_PRELOAD` 

Yeah, this needs to be run on 64bit devices, haven't looked into if there is some elegant way around it.

Closing as it seem to be working (with `tsu` + `unset LD_PRELOAD`)
