### ISSUE TITLE
Not found lspci package

### ISSUE THREAD

**Issue by vida1j** [termux/termux-root-packages#21]
#sudo airmon-ng
Please install lspci from your distro's package manager.
How to solve this?
airmon-ng need lspci package,
Please add lspci package so that we can use aircrack-ng, without lspci, airmon-ng cannot run.

**Comment by Grimler91** [comment]
I believe I just commented out that check when I tried airmon with a usb-dongle.

I can see if it's possible to package pciutils though.

**Comment by Grimler91** [comment]
I've added pciutils to the repo in https://github.com/termux/termux-root-packages/commit/22c7714589e42eea28b10759c991d97c87831f66, and made aircrack depend on it. 

It won't magically give your phone monitor mode abilities though.. :)

**Comment by vida1j** [comment]
Appreciate your work
