### ISSUE TITLE
> E: Unable to locate package libfuse3

### ISSUE THREAD

**Issue by ako123456** [termux/termux-root-packages#215]
> E: Unable to locate package libfuse3
> ./install.sh: 49: ./install.sh: python: not found
> ./install.sh: 50: ./install.sh: pip: not found

I have corrected that, just download again the install.sh
;-)
Bye
Edit : If it still doesn't work, verify that your Wi-Fi works correctly and that you aren't on legacy termux

_Originally posted by @neiviv-ui in https://github.com/termux/termux-root-packages/issues/45#issuecomment-727034753_

**Comment by Grimler91** [comment]
If you cant locate libfuse3 then that's either because you have not installed root-repo, or because you are using android 5 or 6.
