### ISSUE TITLE
What about cryptsetup?

### ISSUE THREAD

**Issue by mxggithub** [termux/termux-root-packages#22]
Hi all.

I'm thinking about the great plus using cryptsetup to open and use on the fly crypted volumes.
Is it possible to have that package available?

Thanks.

**Comment by Grimler91** [comment]
Added in #23.

**Comment by xeffyr** [comment]
cryptsetup fails on loop devices without https://github.com/termux/termux-root-packages/pull/25.

Also, I have found that it is necessary to have `setenforce 0` or the following error will occur:
```
bash-4.4# cryptsetup --cipher=aes-cbc-plain luksFormat /data/test3.img

WARNING!
========
This will overwrite data on /data/test3.img irrevocably.

Are you sure? (Type uppercase yes): YES
Enter passphrase for /data/test3.img: 
Verify passphrase: 
Failed to access temporary keystore device.
```

**Comment by xeffyr** [comment]
With standard Android kernel it is possible to use the following ciphers:
```
aes-cbc-plain
aes-ctr-plain
twofish-cbc-plain
twofish-ctr-plain
```

For using others (e.g. with XTS mode) custom kernel needed.
