### ISSUE TITLE
Error when install root-repo, unable to locate package

### ISSUE THREAD

**Issue by sobaee** [termux/termux-root-packages#227]
this is the error:

![Screenshot_20210224213125](https://user-images.githubusercontent.com/65910585/109048233-e5365c00-76e7-11eb-872c-4cb3dd7c47db.jpg)

Shoud my device be rooted to install it?

**Comment by sobaee** [comment]
Has waorked after I deleted all folders inside HOME directory.

Thanks a lot

**Comment by Grimler91** [comment]
`apt update` might have fixed it as well. Great that it works though. 

And no, you do not need root to install root-repo or any of the packages, but you need root to fully use the installed tools
