### ISSUE TITLE
tshark fail to run on recent version (3.4.3-1), because cannot link executable (libzstd.so.1 not found)

### ISSUE THREAD

**Issue by SNIFFDSO** [termux/termux-root-packages#229]
**Problem description**
Fail to run tshark because cannot link executable (libzstd.so.1 not found) , this happen only on recent version / update tshark / fresh install ,
output when update and executing tshark :
Preparing to unpack .../tshark_3.4.3-1_aarch64.deb ...
Unpacking tshark (3.4.3-1) over (3.4.3) ...
Setting up tshark (3.4.3-1) ...
~ $   tsu
.../files/home # tshark
CANNOT LINK EXECUTABLE "tshark": library "libzstd.so.1" not found
.../files/home # tshark -v
CANNOT LINK EXECUTABLE "tshark": library "libzstd.so.1" not found

**Steps to reproduce**
Fresh install or update tshark , old version didnt affected.
pkg install tshark
tsu
tshark 

**Expected behavior**
tshark running and capturing the selected interface

**Additional information**
termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
Updatable packages:
apt/stable 2.2.0 aarch64 [upgradable from: 2.1.18]
termshark/root 2.2.0-1 aarch64 [upgradable from: 2.2.0]
termux-exec/stable 1:0.9 aarch64 [upgradable from: 1:0.8]
termux-tools/stable 0.112 all [upgradable from: 0.111]
Android version:
9
Kernel build information:
Linux localhost 3.10.108-DarkKnight-g82f74049ab5 #1 SMP PREEMPT Tue Mar 26 00:22:49 IST 2019 aarch64 Android
![a](https://user-images.githubusercontent.com/78293219/109965125-1da9eb80-7d21-11eb-9225-6d50141017d2.png)

**Comment by Grimler91** [comment]
Seems it took the opportunity to link against libzstd.so.1 in the last rebuild. 

You can either install libzstd to make it work, or wait until https://github.com/termux/termux-root-packages/actions/runs/621121864 finishes

**Comment by SNIFFDSO** [comment]
Thanks now its working properly. Awesome
