### ISSUE TITLE
All installation from root-repo failed with output not found

### ISSUE THREAD

**Issue by SNIFFDSO** [termux/termux-root-packages#231]
**Problem description**
Devices cannot install from root repo , when install it will show an eror Unable to locate package ,
tested from Playstore version and Fdroid, already pkg update & upgrade
**Steps to reproduce**
Install any package from root-repo

**Expected behavior**
Package installed succesfully.

![image](https://user-images.githubusercontent.com/78293219/110243375-b09a8e00-7f8c-11eb-8aa1-fb776422e38a.png)

edited : Additional termux-info

termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 3.10.108-DarkKnight-g82f74049ab5 #1 SMP PREEMPT Tue Mar 26 00:22:49 IST 2019 armv8l

**Comment by SNIFFDSO** [comment]
If the package already installed before , it wont upgrade to newest version.

**Comment by Grimler91** [comment]
Have you installed root-repo? 

Try running `apt update` first.

**Comment by SNIFFDSO** [comment]
Yes already updated and installed, for now there is 3 devices that reported the sam,

![image](https://user-images.githubusercontent.com/78293219/110243688-06236a80-7f8e-11eb-8c6a-e7bb1f445c02.png)

**Comment by SNIFFDSO** [comment]
@Grimler91 But some repo still work fine , can it be only for some repo ?

![image](https://user-images.githubusercontent.com/78293219/110243798-84800c80-7f8e-11eb-8f79-e09c7290311e.png)

**Comment by SNIFFDSO** [comment]
Updated about additional termux-info

**Comment by SNIFFDSO** [comment]
All device that eror use fdroid termux, 

this one bellow working is using playstore version and the different is only sources.list repo,
![image](https://user-images.githubusercontent.com/78293219/110244853-4afdd000-7f93-11eb-954d-6226839dcb31.png)

**Comment by Grimler91** [comment]
Some packages are missing from the repo indeed. Will re-upload them

**Comment by Grimler91** [comment]
Should be fixed now, thanks for reporting!

**Comment by SNIFFDSO** [comment]
> Should be fixed now, thanks for reporting!

Anytime , thanks for the response.
