### ISSUE TITLE
Can't install Frida, requires python 3.8 

### ISSUE THREAD

**Issue by n0101** [termux/termux-root-packages#232]
Can't install frida-tools because python-frida can't find pip3.8.  If you install python in termux, 3.9.2 is installed.  Normally on a full linux distro you could apt install python=3.8 but that is not available on termux to my knowledge/testing.

Frida requires python 3.8 according to https://frida.re/docs/building/ so I'm not sure what the solution could be.

**Comment by Grimler91** [comment]
Requires frida to be rebuilt and use 3.9 instead. Rebuilding requires is updating to a newer version though, and I have not gotten that to work yet (requires some new patches, WIP branch at https://github.com/termux/termux-root-packages/tree/frida-14)

**Comment by Grimler91** [comment]
Build now succeeds, but it needs ndk r22 (as fridas sdk is built with that version), so need to solve all the problems related to https://github.com/termux/termux-packages/pull/6174 also
