### ISSUE TITLE
[Bug]: ettercap on /e/ OS fairphone 3

### ISSUE THREAD

**Issue by debian-user-france1** [termux/termux-root-packages#253]
### Problem description

$ etter^C
~ $  sudo ettercap
CANNOT LINK EXECUTABLE "ettercap": library "libformw.so.6" not found

### What steps will reproduce the bug?

$ etter^C
~ $  sudo ettercap
CANNOT LINK EXECUTABLE "ettercap": library "libformw.so.6" not found

### What is the expected behavior?

Should be clear

### System information

Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.218+ #1 SMP PREEMPT Mon Jun 21 12:58:20 UTC 2021 aarch64 Android
Device manufacturer:
Fairphone
Device model:
FP3

**Comment by Grimler91** [comment]
Thanks for reporting, should be fixed in https://github.com/termux/termux-root-packages/commit/76ba533c7d283a94a8a59ba040e4d2f8f3ebabdc, which should be available within an hour
