### ISSUE TITLE
Sniffers do not work on Termux

### ISSUE THREAD

**Issue by Deathlive** [termux/termux-root-packages#27]
Could you solve the problem associated with sniffers?
Earlier I wrote about this here [add package wireless-tools](https://github.com/termux/termux-root-packages/pull/4)
So much time has passed but the problem is still not solved.
The problem is that..
> After launching sudo bettercap -X the program opens, but if the attacking browser goes to any site, then the sites do not load.

I tried another [Xerosploit for Termux](https://github.com/Hax4us/termux-tools/blob/master/dists/termux/extras/binary-all/xerosploit_1.0_all.deb) Same problem.

But in proot debian, there is no such problem.
Simply in the thermalus, there are already iw, wireles-tools, iptables.. 
So why sniffing does not work ?

**Comment by Grimler91** [comment]
Could you specify the problem a bit more, maybe supply a test case? (I'm no expert in wireless-tools/xerosploit/other)

From the discussion in https://github.com/termux/termux-root-packages/pull/4 it sort of feels like the reason it doesn't work is that wireless-tools and other tools are too old/not updated in a long time. In that case it might be better to ask for help upstream/somewhere else, if the problems aren't limited to termux.
