### ISSUE TITLE
package request: kmod

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-root-packages#29]
_From @GIJack on June 15, 2018 15:7_

https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git

kernel tools like lsmod rmmod and modprobe for loading kernel modules are in this package.

useful?

_Copied from original issue: termux/termux-packages#2520_

**Comment by Grimler91** [comment]
_From @tomty89 on June 15, 2018 15:36_

toybox has implementation of them, and it probably belongs to termux-root-packages anyway.

**Comment by GIJack** [comment]
not the same man. want the full GNU user land here. aircrack needs them to run, so it fails

**Comment by tomty89** [comment]
No idea what you are talking about. What's does "GNU user land" has to do with this? Not to mention that you are dealing with an Android kernel build, perhaps the toybox implementation even handles it better.

If a program is expected to run modprobe you need to make sure it's available in PATH, so either have symlink or appropriate wrapper script (see `$PREFIX/bin/logcat` as an example) for it.

If you are supposed to load it yourself, you can even just try `/system/bin/modprobe BLAH` first.

**Comment by GIJack** [comment]
for whatever reason simply running modprobe lsmod, or any of the other linux kernel module tools in termux does not "just work". It works on standard GNU/Linux installs.

**Comment by tomty89** [comment]
Android kernel builds are usually (if not always) way less modular than than those on desktop Linux. Usually only drivers that are out-of-tree or proprietary are made modules. Besides they are mostly loaded/unloaded automatically (either always on or on demand, like turning on/off of wifi).

```
$ find /system -name *.ko 2>/dev/null
/system/lib/modules/ansi_cprng.ko
/system/lib/modules/bcmdhd.ko
/system/lib/modules/brcm_bt_drv.ko
/system/lib/modules/brcm_hci_ldisc.ko
/system/lib/modules/ecryptfs.ko
/system/lib/modules/fm_drv.ko
/system/lib/modules/gpio_axis.ko
/system/lib/modules/gpio_event.ko
/system/lib/modules/gpio_input.ko
/system/lib/modules/gpio_matrix.ko
/system/lib/modules/gpio_output.ko
/system/lib/modules/kscl.ko
/system/lib/modules/mmc_block_test.ko
/system/lib/modules/mmc_test.ko
/system/lib/modules/pronto/pronto_wlan.ko
/system/lib/modules/rdbg.ko
/system/lib/modules/spidev.ko
/system/lib/modules/test-iosched.ko
/system/lib/modules/texfat.ko
/system/lib/modules/wlan.ko
$
```

(`lsmod` doesn't work on Android O unless it is rooted because of the "safer /proc" blah blah)

```
$ /system/bin/modprobe
usage: modprobe [-alrqvsDb] [-d DIR] MODULE [symbol=value][...]

modprobe utility - inserts modules and dependencies.

-a  Load multiple MODULEs
-d  Load modules from DIR, option may be used multiple times
-l  List (MODULE is a pattern)
-r  Remove MODULE (stacks) or do autoclean
-q  Quiet
-v  Verbose
-s  Log to syslog
-D  Show dependencies
-b  Apply blacklist to module names too

modprobe: bad syntax
$
```

In other words, it could be just the kernel was built without whatever you need.

**Comment by MrNobodyTharusha** [comment]
Hey help me...  

# airmon-ng check kill
Your kernel has module support but you don't have modprobe installed.
It is highly recommended to install modprobe (typically from kmod).

Found phy0 with no interfaces assigned, would you like to assign one to it? [y/n] y


 ERROR adding monitor mode interface: command failed: Operation not supported on transport endpoint (-95)

Found phy1 with no interfaces assigned, would you like to assign one to it? [y/n]

Invalid input. Yes, or no? [y/n] y


 ERROR adding monitor mode interface: command failed: Operation not supported on transport endpoint (-95)


#



What happend???

**Comment by MrNobodyTharusha** [comment]
I'm using it on termux

**Comment by Grimler91** [comment]
@MrNobodyTharusha Probably means that those interfaces don't support monitor mode

**Comment by GIJack** [comment]
You can likely close this. airmon-ng will not work on most phones because the kernel drivers don't support monitor and injection mode on most phones. For some phones there have been some work arounds. None will work with termux

**Comment by xeffyr** [comment]
> For some phones there have been some work arounds. None will work with termux

The **only** workaround that will work for most devices with USB OTG is:

* Obtain USB WiFi dongle.
* Obtain kernel sources for your device.
* Enable MAC 80211 drivers in kernel.
* Enable drivers for chipset of your WiFi dongle.
* Search and apply packet injection patches (e.g. from NetHunter).
* Compile & flash kernel.

It worked for my phone and should work for many others as monitor mode is permanently disabled only for built-in dongle.

However, how to get monitor mode goes too far from Termux topics (even for root packages).

**Comment by MrNobodyTharusha** [comment]
So, can't I get any options for it????

**Comment by sidahmed44478** [comment]
my kernel is supported 
but i dont know how to install this "modprobe" and "modinfo" and "rfkill"


# airmon-ng start wlan0
Your kernel has module support but you don't have modprobe installed.
It is highly recommended to install modprobe (typically from kmod).
Your kernel has module support but you don't have modinfo installed.
It is highly recommended to install modinfo (typically from kmod).
Warning: driver detection without modinfo may yield inaccurate results.
Your kernel supports rfkill but you don't have rfkill installed.
To ensure devices are unblocked you must install rfkill.


PHY     Interface       Driver          Chipset

phy0    wlan0           bcmsdh_sdmmc    Broadcom 43430


ERROR adding monitor mode interface: command failed: Operation not supported on transport endpoint (-95)

**Comment by Grimler91** [comment]
@sidahmed44478 Broadcom 43430 doesn't support monitor mode. You need to use another wiri adapter. 

Modprobe, modinfo and rfkill aren't necessary on android.
