### ISSUE TITLE
[Bug]: github action: doesn't compile hwinfo

### ISSUE THREAD

**Issue by Maxython** [termux/termux-root-packages#297]
### Problem description

https://github.com/Maxython/termux-root-packages-pacman/actions/runs/1758192859

### What steps will reproduce the bug?

Empty commit

### What is the expected behavior?

Successful compilation

### System information

This github action

**Comment by xtkoba** [comment]
Seems like hitting https://github.com/openSUSE/hwinfo/issues/103.
