### ISSUE TITLE
Package request: squashfuse

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-root-packages#30]
_From @lars18th on June 8, 2018 13:30_

https://github.com/vasi/squashfuse

The idea is to have the binaries inside the Termux, and with "su" (root) support, mount using native FUSE support an SquashFS image. This will provide _readonly_ mounts of, for example, images inside the SDCard.

The package has native Android support, so I feel it well be easy to incorporate to the Termux Packages repository.

I hope you agree.

_Copied from original issue: termux/termux-packages#2496_

**Comment by Grimler91** [comment]
_From @Quasic on June 19, 2018 18:37_

Maybe this should go in the root package repo?

**Comment by Grimler91** [comment]
_From @lars18th on June 19, 2018 18:52_

> Maybe this should go in the root package repo?

First the package needs to be compiled and checked. Right?

**Comment by Grimler91** [comment]
_From @Quasic on June 19, 2018 22:26_

Someone with root will need to do the checking part. I thought they took requests there, but maybe I'm wrong...

**Comment by Grimler91** [comment]
_From @lars18th on June 20, 2018 7:9_

Hi @Quasic ,

If you say that this request needs to go in the "root package repo" (http://github.com/termux/termux-root-packages), then the answer is: _perhaps_.

The idea is not only "compile" the package. And in this case, for sure it needs to be included in the "root package repo" instead of the "regular termux packages repo". However, the idea goes further!

Let me to explain it:

- If the package really works, that's it compiles and run inside Termux, and using root access you can mount in your device any squashfs image using the FUSE layer... Then you can do a "spplit" of Termux filesystem. And you can generate some read-only images of part of the Termux "filesystem" structure. This will save a lot of space (Squash is a high-compression filesystem), and you can store the images in the SD-CARD (transparently). However, you need to "mount/umount" the images after start/close Termux sessions. And this will include to manage or modify the regular Termux App.

I hope the developers can see the advantage of this mode, and try to add support for this module.

But in any case, the first step is to compile/test/include this module.
Regards.

**Comment by Grimler91** [comment]
_From @Quasic on June 20, 2018 14:10_

Ok, sounds interesting.

**Comment by Grimler91** [comment]
I guess this should go into termux-root-packages, we do compilation/testing there as well. I can move it later. 

It sounds interesting with the possibility to compress and store part of the filesystem elsewhere but not all users are rooted and not everyone can therefore benefit from this/use this.

**Comment by Grimler91** [comment]
_From @lars18th on June 22, 2018 9:16_

Hi @Grimler91 ,

> It sounds interesting with the possibility to compress and store part of the filesystem elsewhere but not all users are rooted and not everyone can therefore benefit from this/use this.

I agree with that! However, I feel it's best to have working the option to store some part of the filesystem compressed in the SD card, and after that explore the options for expand it to non-rooted users. The kernel FUSE support permits a lot of flexibility.

**Comment by Ione75** [comment]
Perhaps

**Comment by Grimler91** [comment]
@lars18th I've added libfuse, squashfuse and encfs to the root repo, but I've barely tested them.

If you feel like testing it squashfuse out (and see how much is possible to do without root) then that would be great. 

If it's useful for none-root users as well then we should definitely move it to the main repo

**Comment by lars18th** [comment]
Great @Grimler91 !

I'll test it.
Thank you!

**Comment by xeffyr** [comment]
@Grimler91 squashfuse prints error `software caused connection abort`:
```
# termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 3.0.101-lineage #1 SMP PREEMPT Thu Nov 9 16:53:29 EET 2017 armv7l Android
Termux-packages arch:
arm
Android version:
7.1.2
Device manufacturer:
samsung
Device model:
GT-I9300
# file image.sqs                                
image.sqs: Squashfs filesystem, little endian, version 4.0, 33554662 bytes, 2 inodes, blocksize: 131072 bytes, created: Wed Oct 17 11:52:13 2018
# squashfuse image.sqs mnt
# ls mnt
ls: mnt: Software caused connection abort
```

**Comment by xeffyr** [comment]
EncFS crashes too:
```
10-17 15:07:34.322  7466  7467 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 7467 (encfs)
10-17 15:07:34.333  7469  7469 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-17 15:07:34.333  7469  7469 F DEBUG   : LineageOS Version: '14.1-20170719-NIGHTLY-i9300'
10-17 15:07:34.333  7469  7469 F DEBUG   : Build fingerprint: 'samsung/m0xx/m0:4.3/JSS15J/I9300XXUGMJ9:user/release-keys'
10-17 15:07:34.333  7469  7469 F DEBUG   : Revision: '0'
10-17 15:07:34.334  7469  7469 F DEBUG   : ABI: 'arm'
10-17 15:07:34.334  7469  7469 F DEBUG   : pid: 7466, tid: 7467, name: encfs  >>> encfs <<<
10-17 15:07:34.334  7469  7469 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
10-17 15:07:34.334  7469  7469 F DEBUG   :     r0 00000001  r1 40bfea28  r2 00000001  r3 40bfe920
10-17 15:07:34.334  7469  7469 F DEBUG   :     r4 406d3000  r5 406dc0e4  r6 00000000  r7 40bfe760
10-17 15:07:34.334  7469  7469 F DEBUG   :     r8 00021000  r9 406a1198  sl 00000000  fp 406a1190
10-17 15:07:34.334  7469  7469 F DEBUG   :     ip 402e40e0  sp 40bfe710  lr 402c839b  pc 400c40a8  cpsr 200f0030
10-17 15:07:34.337  7469  7469 F DEBUG   : 
10-17 15:07:34.337  7469  7469 F DEBUG   : backtrace:
10-17 15:07:34.337  7469  7469 F DEBUG   :     #00 pc 0000a0a8  /data/data/com.termux/files/usr/bin/encfs
10-17 15:07:34.337  7469  7469 F DEBUG   :     #01 pc 00006bef  /data/data/com.termux/files/usr/lib/libfuse.so
```

**Comment by xeffyr** [comment]
> If it's useful for none-root users as well then we should definitely move it to the main repo

@Grimler91 These packages usable only by root, otherwise I'm getting the following error (which is expected):
```
fuse: failed to open /dev/fuse: Permission denied
```

**Comment by FreddieOliveira** [comment]
I've just taken a look into this and was able to compile and use squashfuse successfully. @xeffyr @Grimler91 are you still interested in this? I can make a PR if so.

**Comment by Grimler91** [comment]
@FreddieOliveira a PR would be great!

**Comment by Grimler91** [comment]
Package is available now thanks to @FreddieOliveira!
