### ISSUE TITLE
[Package]: zram-swap

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-root-packages#306]
### Package description

A simple zram swap script for modern systemd Linux

### Source code URL

https://github.com/foundObjects/zram-swap

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Closing since it is just a shell script as @wmcbtech30 pointed out, so it can be quite easily installed from the repo
