### ISSUE TITLE
mtr unable to trace ipv6 addresses

### ISSUE THREAD

**Issue by yangzhaofeng** [termux/termux-root-packages#34]
When I execute 
$ tsudo mtr 2001:da8::666
it says
mtr: Failed to resolve host: 2001:da8::666: No address associated with hostname
if -6 is added
mtr: invalid option -- 6
and attaches a help list
I got mtr from the apt repo in readme.md

**Comment by Grimler91** [comment]
I've updated the package and enabled ipv6 in https://github.com/termux/termux-root-packages/commit/91fecfb89c6f66fc5ca335a2e434bbb3aefe67d8, please do a ˋpkg upgradeˋ and try again!

**Comment by Grimler91** [comment]
I'm assuming it works now.
