### ISSUE TITLE
Add testdisk and photorec

### ISSUE THREAD

**Issue by jbmikk** [termux/termux-root-packages#51]
Being able to recover deleted files from the phone's internal memory would be useful in some cases.

Testdisk and photorec recover lost partitions and deleted files.

1. Home page: https://www.cgsecurity.org/wiki/TestDisk
2. Source code: https://www.cgsecurity.org/wiki/TestDisk_Download

I haven't tried compiling it myself.

**Comment by ShadyGaDa** [comment]
I totally agree. I was trying to compile a simple ext binary recovery utility but got lost in the detail.
There are so many scam merchants on play store.
A until like this would be very useful, as a word processor app the other day decided to delete my Documents folder on removal the other day. Another scam merchant PDF -> docx etc.

**Comment by ShapeShifter499** [comment]
+1 on this request

**Comment by xeffyr** [comment]
Closed by https://github.com/termux/termux-root-packages/pull/159.

Install package with
```
pkg install testdisk
```

**Comment by xcme** [comment]
Is there a way to install it on Android 6.0? I don't see _testdisk_ package in pkg list-all. I don't have **root** too.
P.S. My version is 0.83

**Comment by Grimler91** [comment]
@xcme Not without compiling it yourself. If you are not rooted you will not be able to recover files from the sdcard or attached usb devices.

**Comment by Theoneflop** [comment]
Testdisk does not find any harddisk
