### ISSUE TITLE
docker container

### ISSUE THREAD

**Issue by diehard88** [termux/termux-root-packages#52]
> Note that this currently only works outside of the docker container. To build from the docker container, 
> termux-root-packages has to be a subfolder of termux-packages, and a root package can then be built with
> 

 

This isn't clear to me.  I would like to build tcpdump.

Thank you.

**Comment by Grimler91** [comment]
Hi! How you build it depends on if you are building on ubuntu/archlinux or in the docker used for termux-packages. 

Building outside of docker container
---------------------------------------------

To build tcpdump without the docker container then you can just execute 
```
./build-package.sh tcpdump
```
from the termux-root-packages folder. 

Building in the docker container
---------------------------------------

If you are not using ubuntu/archlinux you need to make use of the docker container that can be downloaded and run from the termux-packages repo. My suggested folder structure/setup would then be to have termux-root-packages as a subfolder of termux-packages, so you could run:
```
git clone https://github.com/termux/termux-packages
cd termux-packages
git clone https://github.com/termux/termux-root-packages
```
to get that structure.

From the termux-packages folder you can then build tcpdump with: 
```
./scripts/run-docker.sh ./build-package.sh termux-root-packages/packages/tcpdump
```

This structure is a bit annoying as you then have termux-packages at two places, both as a submodule of termux-root-packages and in the parent directory. I want to improve this but haven't yet decided on the best solution.

--------------------

Was that clearer? I'll look at improving the README!

**Comment by diehard88** [comment]
thanks.... now it's clear...   I believed that one could only compile android files inside android.

to finalize this, one last question:

if the ubuntu/archlinux is x32/x64, will it compile the above with ARM instruction set?

**Comment by xeffyr** [comment]
> will it compile the above with ARM instruction set?

NDK is cross-compiler so it *will* compile.
The only requirement is **x86_64** machine (& OS) because Android NDK is for *x86_64*.

**Comment by diehard88** [comment]
thx!
