### ISSUE TITLE
mkdir: can't write to directory : read only file system

### ISSUE THREAD

**Issue by Joe-Degs** [termux/termux-root-packages#70]
Termux csnt write files to the storage even though it has storage permission

**Comment by Grimler91** [comment]
I don't know which folder you are trying to write to but this isn't anything related to termux. You can perhaps re-mount the folder as read&write from adb: https://android.stackexchange.com/questions/110927/how-to-mount-system-rewritable-or-read-only-rw-ro

The external and internal storage is writeable as root.
