### ISSUE TITLE
package request: wifite2

### ISSUE THREAD

**Issue by huitc** [termux/termux-root-packages#72]
Great job for all that Termux is. I know that this is probably a "no can do", but would be a for a nobel award!

;)

**Comment by Grimler91** [comment]
Hi, wifite is a python module and we generally don't package python modules.

Have you tried installing it on device?

**Comment by huitc** [comment]
https://github.com/termux/termux-root-packages/issues/71
@Grimler91

**Comment by huitc** [comment]
How to install dependencies? (WIFITE2) @Grimler91 How to install dependencies? (WIFITE2) @Grimler91
