### ISSUE TITLE
package request: fusermount

### ISSUE THREAD

**Issue by rodibin-at-placemaildotonline** [termux/termux-root-packages#73]
Package is required for `rclone mount` to function correctly, which is already a termux package. It also helps expand the termux package universe by allowing other packages to be utilized and installed, like #74

**Package description**
fusermount is a simple interface for userspace programs to export a virtual filesystem to the Linux kernel

**Link to home page and sources**
1. Home page: https://github.com/libfuse/libfuse
2. Source code:
https://github.com/LineageOS/android_external_fuse/tree/cm-14.1
https://github.com/refi64/zdata/blob/master/fs/jni/fusermount.mk

**Additional information**
Have you compiled or tried to compile the package on device?
Compiled here, works great, just hoping we can bring it to the mainline repository for termux: https://forum.xda-developers.com/android/development/fusermount-android-rclone-mount-t3866652

**Comment by xeffyr** [comment]
It is part of package `libfuse` which is disabled for now.

**Comment by rodibin-at-placemaildotonline** [comment]
great, any reason why libfuse is disabled? can't find it anywhere in the disabled notes

**Comment by Grimler91** [comment]
@rodibin-at-placemaildotonline see https://github.com/termux/termux-root-packages/issues/30. I applied some pretty weird patches to get it compiling, need to give it some more love. See also discussion in https://github.com/termux/termux-root-packages/issues/45 (and in particular https://github.com/termux/termux-root-packages/issues/45#issuecomment-343376355)

**Comment by rodibin-at-placemaildotonline** [comment]
FYI someone compiled fusermount for android here

https://forum.xda-developers.com/android/development/fusermount-android-rclone-mount-t3866652

**Comment by jrop** [comment]
Any love for this planned in 2020?  Just curious...
