### ISSUE TITLE
package request: Realtek RTL8812AU driver

### ISSUE THREAD

**Issue by huitc** [termux/termux-root-packages#75]
https://www.edimax.com/edimax/mw/cufiles/files/download/Driver_Utility/EW-7811UTC_UAC_DAC_USC_Linux_Driver_1.0.2.4.zip

https://github.com/aircrack-ng/rtl8812au

https://github.com/aircrack-ng/rtl8812au/issues/299

https://wikidevi.com/wiki/Tenda_U12

https://github.com/ZerBea/hcxdumptool/issues/42#issuecomment-473568812

**Comment by huitc** [comment]
Working on actual kernel 4.19, 4.20, 5.0
Not working on 5.1 and kernel < 4.19
You can follow progress here:
openwrt/mt76#216

**Comment by Grimler91** [comment]
We can't add a package such as this as it needs to be compiled together with the kernel sources, and we don't have those available. 
I am also not sure if dkms would work on android.

Only way to get the driver is to compile your own kernel and configure the driver there.
