### ISSUE TITLE
package ethtool always "upgradable"

### ISSUE THREAD

**Issue by huitc** [termux/termux-root-packages#81]
`ethtool/root 4.19 aarch64 [upgradable from: 4.19]`

**Comment by huitc** [comment]
you can fix it by `update` and `upgrade`

**Comment by huitc** [comment]
and package request: `linux-headers-*`

`Linux localhost 4.4.78-perf-ge57b3e5 #1 SMP PREEMPT Thu Mar 21 03:44:54 CST 2019 aarch64 Android`
android 8.0.0

**Comment by Grimler91** [comment]
We can't package `linux-headers`, they are unique for each device.
