### ISSUE TITLE
package request: wifite2, Realtek RTL8812AU driver

### ISSUE THREAD

**Issue by huitc** [termux/termux-root-packages#87]
https://github.com/derv82/wifite2
https://github.com/aircrack-ng/rtl8812au
pls and thx!!😅

**Comment by huitc** [comment]
```
$ lsusb
Bus 001 Device 002: ID 2604:0012
Bus 001 Device 001: ID 1d6b:0002
Bus 002 Device 001: ID 1d6b:0003
```

**Comment by Grimler91** [comment]
Why are you opening duplicate issues? I've already commented on this in https://github.com/termux/termux-root-packages/issues/72 and https://github.com/termux/termux-root-packages/issues/75

**Comment by huitc** [comment]
How to install dependencies? (WIFITE2) @Grimler91 How to install dependencies? (WIFITE2) @Grimler91
