### ISSUE TITLE
Package request: fping

### ISSUE THREAD

**Issue by freddykindell** [termux/termux-root-packages#91]
**Package description**
fping is a program to send ICMP echo probes to network hosts, similar to ping, but much better performing when pinging multiple hosts. fping has a very long history: Roland Schemers did publish a first version of it in 1992 and it has established itself since then as a standard tool for network diagnostics and statistics.

**Link to home page and sources**
1. Home page: https://fping.org/
2. Source code: https://github.com/schweikert/fping

**Additional information**
Have you compiled or tried to compile the package on device?
No. But, if you guys has try it, please help me and let me know. i really need this package. thanks.

**Comment by Grimler91** [comment]
Hi, 
I won't be able to add fping to the repos as it has a none-standard license, and [Bintray](https://bintray.com/grimler/termux-root-packages-24)'s open-source account type only support a certain set of licenses (listed at the bottom of this page: https://bintray.com/docs/api/#_delete_docker_tag) 

Fortunately compiling on device seem to be straight forward, clone the repo, run `./autogen.sh`, then `./configure` and `make`. You probably need to install libcap and run `setcap cap_net_raw+ep path/to/fping` as root as well.

I ran some tests but wasn't able to make it work though, it fails with an system call failure that I haven't been able to track the origin of.

**Comment by AbdullahBinJahed** [comment]
did it worked ???

**Comment by AbdullahBinJahed** [comment]
> **Package description** fping is a program to send ICMP echo probes to network hosts, similar to ping, but much better performing when pinging multiple hosts. fping has a very long history: Roland Schemers did publish a first version of it in 1992 and it has established itself since then as a standard tool for network diagnostics and statistics.
> 
> **Link to home page and sources**
> 
> 1. Home page: https://fping.org/
> 2. Source code: https://github.com/schweikert/fping
> 
> **Additional information** Have you compiled or tried to compile the package on device? No. But, if you guys has try it, please help me and let me know. i really need this package. thanks.

did it worked ???
