### ISSUE TITLE
Tshark question

### ISSUE THREAD

**Issue by HoangPhantom** [termux/termux-root-packages#93]
I was trying tshark and I see this. Is this something that can stop me.

tshark: Couldn't load plugin 'usbdump.so': dlopen failed: cannot locate symbol "wtap_register_open_info" referenced by "usbdump.so"...

**Comment by Grimler91** [comment]
What is the output of `termux-info` on your device?

**Comment by HoangPhantom** [comment]
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-21 unstable/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.72 #1 SMP PREEMPT Tue Feb 16 18:23:49 CST 2016 armv7l Android
Termux-packages arch:
arm
Android version:
5.1
Device manufacturer:
Lenovo
Device model:
Lenovo TB3-710I

**Comment by HoangPhantom** [comment]
It doesn't stop me much but I don't know if it restricts me from some other features

**Comment by Grimler91** [comment]
You can probably use `LD_PRELOAD=$PREFIX/lib/libwiretap.so your-tshark-command` before I can push a fix. 

Looks like it's not linking correctly for some reason, even though the CMakeLists.txt explicitly links usbmon against libwiretap.

**Comment by HoangPhantom** [comment]
I see, thank you very much. But it's a little bit annoying that we have to enter a few more commands.

**Comment by Grimler91** [comment]
tshark 3.0.1 is now available from the android-7 branch, and should be available from the android-5 repo in 15 minutes or so.

**Comment by HoangPhantom** [comment]
After upgrading

**Comment by HoangPhantom** [comment]
Tshark no longer executes after upgrading

**Comment by Grimler91** [comment]
Could you be a bit more specific?

**Comment by Grimler91** [comment]
Closing as the original issue is solved

**Comment by HoangPhantom** [comment]
It doesn't output anything

**Comment by Grimler91** [comment]
> It doesn't output anything

That "information" doesn't help me reproduce the issue and it seems to work on my device.

**Comment by HoangPhantom** [comment]
That is indeed strange as it doesn't for my device

**Comment by HoangPhantom** [comment]
My apologies for replyig late. When I enter the command, it just puts me back at the usual shell. It doesn't output anything about Tshark.

**Comment by Grimler91** [comment]
@HoangPhantom Please have a look at the [bug report template](https://github.com/termux/termux-root-packages/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and open a new issue.

**Comment by HoangPhantom** [comment]
Ok, I'll try to make it more verbose in the new issue
