### ISSUE TITLE
A Tshark bug report

### ISSUE THREAD

**Issue by HoangPhantom** [termux/termux-root-packages#95]
Tshark:
When I try to execute tshark, it won't output anything at all. After execution, it just puts back the shell. I expected it to print something, but it doesn't do anything at all. Here is a screenshot. I hope this is enough for you to reproduce and understand what is the matter of this package.
![Screen_Capture_Img_583](https://user-images.githubusercontent.com/46418295/58251138-2b30f400-7d8d-11e9-87d7-f9660f688ab2.png)

**Comment by xeffyr** [comment]
1. Why you are launching tshark from regular shell ? It's a package that require root.

2. Regarding https://github.com/termux/termux-root-packages/issues/93, @Grimler91 that issue a bug/feature of dlopen() on Android. Workaround is available in my x11/wireshark-gtk package, see patches in https://github.com/termux/x11-packages/tree/master/packages/wireshark-gtk.

**Comment by HoangPhantom** [comment]
In an older version, I managed to do it without root. But now even with root, it's still the same
![Screen_Capture_Img_7544](https://user-images.githubusercontent.com/46418295/58254195-697de180-7d94-11e9-87c5-d95508760476.png)

**Comment by xeffyr** [comment]
@HoangPhantom What your tshark version ? On all my devices `tshark` v3.0.1 works fine.

**Comment by HoangPhantom** [comment]
Just like yours: 3.0.1

**Comment by HoangPhantom** [comment]
Can my device's info help

**Comment by Grimler91** [comment]
> Regarding #93, @Grimler91 that issue a bug/feature of dlopen() on Android. Workaround is available in my x11/wireshark-gtk package, see patches in https://github.com/termux/x11-packages/tree/master/packages/wireshark-gtk.

Yeah, I figured, updating to 3.0.1 felt easier though since the cmake system fixes it :)

**Comment by Grimler91** [comment]
@HoangPhantom What do you even want to dump? Select the interface with `tshark -i {something}`.

Check for available interfaces with `dumpcap -D`.

**Comment by HoangPhantom** [comment]
Can you show me the syntax of the command to fix it.

**Comment by HoangPhantom** [comment]
Oh and neither tshark nor dumpcap output anything

**Comment by Grimler91** [comment]
What does `gdb -ex r --args dumpcap -D` or `gdb -ex r --args tshark` tell you?

**Comment by HoangPhantom** [comment]
Please wait while I install gdb

**Comment by HoangPhantom** [comment]
Here is screenshot. 
![Screen_Capture_Img_7319](https://user-images.githubusercontent.com/46418295/58256171-bfed1f00-7d98-11e9-8a81-d21bf9ecccf6.png)
![Screen_Capture_Img_9627](https://user-images.githubusercontent.com/46418295/58256190-cb404a80-7d98-11e9-81c9-bf6766f70f42.png)

**Comment by HoangPhantom** [comment]
Nevermind, I restarted Termux and it worked again. Thank you anyways for your dedication and for taking your time to help all Termux users
